### ISSUE TITLE
No properties when accessing File through ListItem

### ISSUE THREAD

**Issue by domdinicola** [vgrem/Office365-REST-Python-Client#132]
When I check properties of a file through ListItem I get no properties..
Is there a way to get the file related to a ListItem and related properties?

>> obj
>> <office365.sharepoint.listitem.ListItem object at 0x7f6ac94d2f28>
>> obj.file
>> <office365.sharepoint.file.File object at 0x7f6ac8babef0>
>> obj.file.properties
>> {}

**Comment by domdinicola** [comment]
@vgrem is this feasible?

**Comment by florinmihut** [comment]
Seems to me that the generated URL is wrong and the server returns an error.
To reproduce this just do:
```
list_obj = ctx.web.lists.get_by_title("Some list")
qry = CamlQuery.create_all_items_query()
items = list_obj.get_items(qry)
ctx.execute_query()
for item in items:
  file = item.file
  ctx.load(file)
  ctx.execute_query()
```
And an exception is triggered because the REST used is (if the Id of the item is 9)
https://my.sharepoint.com/sites/Test/_api/Web/lists/GetByTitle('Some list')/items/getItemById(9)
which returns an error. 
It should be something like:
https://my.sharepoint.com/sites/Test/_api/Web/lists/GetByTitle('Some list')/getItemById(9)
An workaround is:
```
item_for_file = list_obj.get_item_by_id(item.properties['Id'])
file = item.item_for_file 
ctx.load(file)
ctx.execute_query()
```
Not sure about the fix ...

**Comment by florinmihut** [comment]
With the latest from git, this seems to be fixed too. 
I can't reproduce the error anymore with the code above. No need for workaround either.

**Comment by domdinicola** [comment]
Hopefully we will have a release soon

**Comment by vgrem** [comment]
Greetings!

@domdinicola, this is expected behavior, navigation properties (e.g. `ListItem.File` property ) are not retrieved by default, they need to be explicitly retrieved via [`$expand` query option](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/fd1f888b-a2e5-4f00-baf9-d2b8cdf1ee91) like this:


```
list_item = ctx.web.lists.get_by_title("Documents").get_item_by_id(item_id).expand(["File"])
ctx.load(list_item)
ctx.execute_query()
print(list_item.file.properties['Name']) # print file name
```



@florinmihut , one of the most beneficial way (_from performance perspective since it requires a **single** request to the server_) to retrieve items along with associated files could be like this:


```
library = ctx.web.lists.get_by_title("Documents")
items_for_files = source_library.items.filter("FSObjType eq 0").select(["File"]).expand(["File"])
ctx.load(items_for_files)
ctx.execute_query()

# download files
download_path = tempfile.TemporaryDirectory()
for item in items_for_files:
    file = item.file #get associated file entity


```

**Comment by domdinicola** [comment]
@vgrem I tried to apply extra on List.get_items() (which returns a ListItemCollection, get_item_by_id returns a ListItem), is there any way to get the File on this (my need is to get a list of items and get the file download link)

**Comment by domdinicola** [comment]
@vgrem can you provide any advice on this?

**Comment by domdinicola** [comment]
@vgrem this is not closed... can this work on ListItems?
