### ISSUE TITLE
Sharepoint 403 for "/_api/web"

### ISSUE THREAD

**Issue by msisson** [vgrem/Office365-REST-Python-Client#138]
I'm following the sample code from your readme and getting a 403 when I try to access the "/_api/web" endpoint (see section below).  I can't get to this in a browser either (says I don't have access).  Is this because my company does not allow api access for users?  Does this mean I can't use this library to access Sharepoint files?

I was able to get graph queries to work using [this sample app](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/app.py
). I didn't like this sample though because it required that I register an application and used flask to interact with me in a browser (via flask) to do an OAuth login.  My goal is to have a headless app that I can run nightly to go pull sharepoint files using my credentials.

What library is best for what I'm trying to do?

Mark

```
import json
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.runtime.client_request import ClientRequest
from office365.runtime.utilities.request_options import RequestOptions
username = 'MYNAME@MYCOMPANY.com'
password = '***'

url = 'https://OURCOMPANY.com'
ctx_auth = AuthenticationContext(url)

if ctx_auth.acquire_token_for_user(username, password):
  request = ClientRequest(ctx_auth)
  options = RequestOptions("{0}/_api/web/".format(url))
  options.set_header('Accept', 'application/json')
  options.set_header('Content-Type', 'application/json')
  data = request.execute_request_direct(options)   #<==THIS RETURNS A 403
  s = json.loads(data.content)
  web_title = s['Title']
  print("Web title: " + web_title)
else:
  print(ctx_auth.get_last_error())
```

**Comment by msisson** [comment]
I'm making a little progress but still have question.  I tried accessing the "/_api/web" from a sharepoint folder and now that works in my browser but still not in code.   My browser can access this:

`https://OURCOMPANY.com/teams/OURFOLDER/_api/web/`

But my code above gets a 404 with that url.

`Cannot find resource for the request _api.`

**Comment by vgrem** [comment]
Greetings!

Regarding 

> I was able to get graph queries to work using this sample app. 

indeed, the provided example demonstrates how  to access resources [on behalf of a user](https://docs.microsoft.com/en-us/graph/auth-v2-user) and it requires user to sign in via browser.  


> My goal is to have a headless app that I can run nightly to go pull sharepoint files using my credentials.

I believe what you are after is  _OAuth 2.0 client credentials grant flow_ which is explained in [Get access without a user](https://docs.microsoft.com/en-us/graph/auth-v2-service) article. 


Now comes the turn of downloading a file from SharePoint Online, indeed, the library supports    _user credentials flow_ to access SharePoint resources and a file could be downloaded like this:

```

    ctx_auth = AuthenticationContext(url=site_url)
    if ctx_auth.acquire_token_for_user(username=username,
                                       password=password):
        ctx = ClientContext(site_url, ctx_auth)
        response = File.open_binary(ctx, "/teams/OURFOLDER/Shared Documents/Guide.docx")
        with open("./data/Guide.docx", "wb") as local_file:
            local_file.write(response.content)

```

Note:
 - it is assumed the file is located in `Documents` library, that's why path to file is specified as 
`/teams/OURFOLDER/Shared Documents/Guide.docx`
