### ISSUE TITLE
outlook api example

### ISSUE THREAD

**Issue by segalion** [vgrem/Office365-REST-Python-Client#148]
You say this package support outlook o365 api.

Could you post an example over 'https://outlook.office365.com/' api?

Seeing inside code, and seems most things are uncompleted.

I am searching for access outlook office365 api with an "application password" access.

Thanks in advance.

**Comment by vgrem** [comment]
Greetings!

[Outlook Mail REST API](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations) is supported but you're right, _not all the actions and operations are covered yet_.

Regarding your request:

> I am searching for access outlook office365 api with an "application password" access.

Below is demonstrated how to acquire a token via [Client Credential flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) and initialize a client:  


```
def get_token(auth_ctx):
    token = auth_ctx.acquire_token_with_client_credentials(
        "https://graph.microsoft.com",
        client_id,
        client_secret)
    return token


tenant_name = "mediadev8.onmicrosoft.com"
client = GraphClient(tenant_name, get_token)
```



Here is a sample which demonstrates how to [send email](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations#create-and-send-messages):



```
import os
from office365.graph_client import GraphClient


def get_token(auth_ctx):
    token = auth_ctx.acquire_token_with_client_credentials(
        "https://graph.microsoft.com",
        client_id,
        client_secret)
    return token


tenant_name = "contoso.onmicrosoft.com"
client = GraphClient(tenant_name, get_token)

message_payload = {
    "Message": {
        "Subject": "Meet for lunch?",
        "Body": {
            "ContentType": "Text",
            "Content": "The new cafeteria is open."
        },
        "ToRecipients": [
            {
                "EmailAddress": {
                    "Address": "vgrem@mediadev8.onmicrosoft.com"
                }
            }
        ],
        "Attachments": [
            {
                "@odata.type": "#Microsoft.OutlookServices.FileAttachment",
                "Name": "menu.txt",
                "ContentBytes": "bWFjIGFuZCBjaGVlc2UgdG9kYXk="
            }
        ]
    },
    "SaveToSentItems": "false"
}

login_name = "mdoe@mediadev8.onmicrosoft.com"
client.users[login_name].send_mail(message_payload)
client.execute_query()
```

And last but not least, please make sure  to grab [`2.1.5` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.5) or later since since `GraphClient` has been introduced in this release
