### ISSUE TITLE
MoveTo

### ISSUE THREAD

**Issue by gwheeler1974** [vgrem/Office365-REST-Python-Client#157]
I need to move a file from one Sharepoint folder to another.  I have an older version of Office365-REST-Python-Client that had a move command and that work fine, but one of the parms was to pass it the original file.  That doesn't seem to be part of MoveTo.  Can anyone help me with an example.  I'm going crazy trying to figure this out.

**Comment by vgrem** [comment]
Greetings!

sorry it caused the confusion, in fact the single purpose of this sdk is quite the opposite,  to make it working with Office 365 API in the most simple and straightforward manner. Apparently the  mission is not even close to considered accomplished.


Here is an example on how to move file into a sub folder  

```
ctx = ClientContext(site_url, ctx_auth)
# get a source file located in library 'Shared Documents'
source_file = ctx.web.get_file_by_server_relative_url("/teams/Team123/Shared Documents/Guide.docx")
# move a file into sub folder called 'Archive'
source_file.moveto("/teams/Team123/Shared Documents/Archive/Guide.docx", 1)
# execute a query
ctx.execute_query()

```
**Comments:**

- both `moveto` and  `get_file_by_server_relative_url`  methods accept _the server relative url to a file_ which must contain site segment as well 


- a second argument for `moveto` method accept value `1` which means "Overwrite a file with the same name if it exists."


**Result** 

![image](https://user-images.githubusercontent.com/1596072/70611536-06f41200-1c0e-11ea-88dd-ae7b9fc8c4da.png)

**Comment by sameh-sharaf** [comment]
Thank you for the example. This is the only code snippet I could find when looking for the answer. Could you please add this to the example's folder?

**Comment by AnjeshSingh** [comment]
Do we have a snippet to copy a file from one home directory to a different home directory of the same Sharepoint? Both directories will have different client IDs and secrets.
sourcepath = abc.com/teams/Team123/Shared Documents/Guide.docx
destination = abc.com/sites/Team456/TheDocuments/Guide.docx

**Comment by DaleAlphonso** [comment]
Before June 30th, 2023 The moveTo function was moving the files within the sharepoint folders. But after 1st July , 2023 , its not moving the files and giving the error as ('-2147024891, System.UnauthorizedAccessException', 'Access denied.', "403 Client Error: Forbidden for url:.....). I checked there are required access as It does other operations like delete and other. I guess the issue is with office365 python package.

**Comment by JimPfening** [comment]
I am running into the same issue as @DaleAlphonso -- Access denied on the moveto function.  I can upload, download and delete files in the folders, but the moveto function results in the Access denied error.  As a work around I can download the file, upload the file to the archive folder, then delete the file from the original folder and from the local folder.  

I am not sure about the exact dates that Dale reported.  But it did work for me at the beginning of June and has been returning an error since the middle of July.

Has anybody else run into this?

**Comment by JimPfening** [comment]
This issue (#157) is closed.  There is a new issue that is open and labeled as a bug.  Please see this new issue for a possible work around: https://github.com/vgrem/Office365-REST-Python-Client/issues/703
