### ISSUE TITLE
Help | need assistance for sharepoint (file upload)

### ISSUE THREAD

**Issue by mstankovic** [vgrem/Office365-REST-Python-Client#164]
Hi,

Im very new to python and python's libraries.. I found this API useful for uploading a file to sharepoint but im not able to do that..

readme.md file in not for absolute beginners so please help me with this.

I have installed library using `pip install Office365-REST-Python-Client` but i dont know what next to do?

I tried to checkout this repo and go to examples/sharepoint and try to execute `file_upload_session.py` but without success. 

Please help me to upload file to the my sharepoint online. Thanks

**Comment by vgrem** [comment]
Greetings!

in the latest version (`2.1.6` or above) which which hides all the intricacies related with [Upload large files](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-large-files-sample-app-for-sharepoint) implementation, the example for uploading a file as 1MB chunks could be represented like this:


```
ctx = ClientContext(site_url, ctx_auth)

size_1Mb = 1000000
local_path = "./data/big_buck_bunny.mp4"
target_url = "/Shared Documents"
result_file = ctx.web.get_folder_by_server_relative_url(target_url).files.create_upload_session(local_path, size_1Mb, print_upload_progress)
ctx.execute_query()
print('File {0} has been uploaded successfully'.format(result_file.properties['ServerRelativeUrl']))

```

where 

```
def print_upload_progress(offset):
    print("Uploaded '{0}' bytes...".format(offset))
```


Example: [`file_upload_session.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/file_upload_session.py)


**Regarding latest version**

Since [we are experiencing some troubles](https://github.com/vgrem/Office365-REST-Python-Client/issues/167) with releasing a new version to PyPi, i would recommend to install  the latest version from GitHub at the moment:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`



And sorry for the delay with response,
Vadim
