### ISSUE TITLE
How to get file's author login?

### ISSUE THREAD

**Issue by pvoloshyn** [vgrem/Office365-REST-Python-Client#166]
Hi, I'm trying to list some properties like 'Author' or 'ModifiedBy' with more information like LoginName from a `File` object, but I can't figure out how to get a `User` object from these properties.

```
file = folder.files.get_by_url('SampleFile.docx')
ctx.load(file)
ctx.execute_query()
print("File author: {0}".format(file.properties['Author']))
```

Is there any suggestion?

**Comment by pvoloshyn** [comment]
After many attempts I figure out that I need to expand 'Author' and it answered my question.

```
file = folder.files.get_by_url('SampleFile.docx').expand('Author')
ctx.load(file)
ctx.execute_query()
print("File author: {0}".format(file.properties['Author']['UserPrincipalName']))
```

Nice lib anyway! Tks

**Comment by vgrem** [comment]
Greetings,

that's right, since `Author` is a _lookup_ field is not returned by default, utilizing `$expand` query option allows to return it as a projected field from `User Information List` (system  list where users are stored). 

From [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#query-for-single-value-lookup-fields):

> You can also specify that the request returns projected fields from other lists and the values of lookups. To do this, specify the field name in both the $select and $expand query options.
