### ISSUE TITLE
The service token could not be extracted from the XML response.

### ISSUE THREAD

**Issue by michalz92** [vgrem/Office365-REST-Python-Client#169]
I copy-pasted the first and second examples from the readme, and this is what I get. The url I provided is of the form:

`url = "https://my-company.sharepoint.com"`

**Comment by OFFICE365USER** [comment]
What version are you running? "pip show Office365-REST-Python-Client"
Might be this: https://github.com/vgrem/Office365-REST-Python-Client/issues/174

**Comment by vgrem** [comment]
Greetings!

Are you experiencing this error while trying to connect with _user credentials_, if so then as @OFFICE365USER  pointed out  there is an issue with authenticating on non root site collection or a sub site.

But not any longer, since pip has not yet been updated, make sure to grab the latest version from GitHub instead:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git `


Btw, the url `https://my-{tenant}.sharepoint.com` refers to MySite host site collection, you probably want to access your OneDrive  instead, then the url should be: 

https://{tenant}-my.sharepoint.com/personal/{username}_{tenant}_onmicrosoft_com/ 


**Example**
   
    tenant_name = "contoso"
    password = "--password goes here--"
    username = "jdoe@contoso.onmicrosoft.com"

    client = getMyDriveClient(tenant_name, username, password)
    client.load(client.web)
    client.execute_query()
    print(client.web.properties['Url'])

where

```
def getMyDriveClient(tenant_name, user_principal_name, password):
    user_name = user_principal_name.split('@')[0]
    my_drive_url = "https://{0}-my.sharepoint.com/personal/{1}_{0}_onmicrosoft_com/".format(tenant_name, user_name)
    return ClientContext.connect_with_credentials(my_drive_url, UserCredential(user_principal_name, password))

```
