### ISSUE TITLE
Bad Request for URL when dowloading file

### ISSUE THREAD

**Issue by rebeccaebarnes** [vgrem/Office365-REST-Python-Client#182]
I'm trying to download a file from our SharePoint site but have been unsucessful so far. I've been able to successfully upload to the site using the same authentication method as below.

I've used the code from [file_operations.py](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/file_operations.py)

**Supplied Code**
```
org_url = 'https://my_org.sharepoint.com'
site_url = '/sites/my_site'
auth = # Created using example code - just uses org_url
ctx = ClientContext(org_url + site_url, auth)
response = File.open_binary(ctx, "Shared Documents/Test doc.docx")
```
The response is a 400 error: Specified value is not supported for the serverRelativeUrl parameter.

**I also tried just getting the file url**
```
ctx = ClientContext(org_url + site_url, auth)
file = ctx.web.get_file_by_server_relative_url('Shared Documents/Test doc.docx')
ctx.load(file)
ctx.execute_query()
```
This also produces a 400 error: Bad Request for url: https://my_org.sharepoint.com/sites/sites/my_site/_api/Web/getfilebyserverrelativeurl('Shared%20Documents%2FTest%20doc.docx')

Any advice on what I need to be doing differently to read the file?

**Comment by vgrem** [comment]
Hello,

this (misleading) error most likely occurs since `File.open_binary` and `Web.get_file_by_server_relative_url` methods expects _server relative file url_. 

For instance, if a file is located in a `Documents `library on `https://my_org.sharepoint.com/sites/sites/my_site`  site then the following url need to be provided:

`response = File.open_binary(ctx, "sites/sites/my_site/Shared Documents/Test doc.docx")`





 


P.S. Apology for the late response,
Vadim

**Comment by rebeccaebarnes** [comment]
Thanks! Working out the difference in the relative address for the file and the folder had me confused, but this helped get it working.
