### ISSUE TITLE
Unable to download File - Error 400

### ISSUE THREAD

**Issue by sibi-cb** [vgrem/Office365-REST-Python-Client#186]
![image](https://user-images.githubusercontent.com/60815801/80298479-5cd6ea00-87aa-11ea-8d3d-fa623b648f1c.PNG)
Hi I am trying to download an excel file from Sharepoint with the following python code.

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.file import File
app_settings = {
    'url': 'https://xxxxx/sites/DownloadFiles',
    'client_id': 'xxxxxx',
    'client_secret': 'xxxxxx',
}
if __name__ == '__main__':
    ctx_auth = AuthenticationContext(url=app_settings['url'])
    ctx_auth.acquire_token_for_app(client_id=app_settings['client_id'], client_secret=app_settings['client_secret'])
    ctx = ClientContext(app_settings['url'], ctx_auth)

    path = "F:\myexcel.xlsx"
    response = File.open_binary(ctx, "/Shared%20Documents/myexcel.xlsx")
    response.raise_for_status()
    with open(path, "wb") as local_file:
        local_file.write(response.content)

And I'm getting the following error

400 Client Error: Bad Request for url: https://xxx/DownloadFiles/_api/web/getfilebyserverrelativeurl('/Shared%20Documents/myexcel.xlsx')/%5C$value

Please help me what I'm doing wrong

**Comment by vgrem** [comment]
Greetings,

the error most likely occurs since  `File.open_binary` method expects _server relative url to a file.
Meaning since file resides on non root site collection, a file needs to be addressed like this: 

`response = File.open_binary(ctx, "/sites/DownloadFiles/Shared%20Documents/myexcel.xlsx")`



Btw, starting from [`2.1.8` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.8) introduced a simplified way to initialize authenticated client, so instead of 

```
ctx_auth = AuthenticationContext(url=app_settings['url'])
ctx_auth.acquire_token_for_app(client_id=app_settings['client_id'], client_secret=app_settings['client_secret'])
ctx = ClientContext(app_settings['url'], ctx_auth)
```
a client could be initialized like this:

```
ctx = ClientContext.connect_with_credentials(app_settings['url'],
                                             ClientCredential(app_settings['client_id'], app_settings['client_secret']))
```

**Comment by andresgd7** [comment]
Try to generate the connection context again before doing any crud operation in sharepoint if you get this error. A try/catch works for me, i cant find a better way to fix this.
