### ISSUE TITLE
Problem to use UserCredential and RequestOptions

### ISSUE THREAD

**Issue by RafaelFleming** [vgrem/Office365-REST-Python-Client#229]
Hello,

I try use the block from exemples:

> import json
> from office365.runtime.auth.UserCredential import UserCredential
> from office365.runtime.http.request_options import RequestOptions
> from office365.sharepoint.client_context import ClientContext
> 
> ctx = ClientContext(site_url).with_credentials(UserCredential(username, password))
> request = RequestOptions("{0}/_api/web/".format(settings['url']))
> response = ctx.execute_request_direct(request)
> json = json.loads(response.content)
> web_title = json['d']['Title']
> print("Web title: {0}".format(web_title))

But I get a problem with UserCredential and RequestOptions. This functions have been discontinued?

Tks

**Comment by vgrem** [comment]
Greetings!

In the latest version (`2.2.0` at the moment)  `UserCredential` class needs to be imported like this:

`from office365.runtime.auth.user_credential import UserCredential`

instead of: 

`from office365.runtime.auth.UserCredential import UserCredential`

Other than that, no API design changes have been made and not expected in foreseeable future.

It appears you experience the same issue as was reported [here](https://github.com/vgrem/Office365-REST-Python-Client/issues/255), and related with _out-dated_ package which is available via default package index:

`pip install Office365-REST-Python-Client`


My recommendation to install the _latest version_ (`2.2.0`) from alternative index instead:

`pip install office365-rest-client`

or from GitHub directly:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

  
And to avoid this kind of confusion, the installation instruction section has been updated in this regard for [`Readme.md`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/README.md):


> Due to the lengthy delay with updating `Office365-REST-Python-Client` PyPI package to the latest version, prefer nowadays an alternative index instead to install the latest version:
> 
> `pip install office365-rest-client`
> Alternatively the latest version could be installed directly via GitHub:
> 
> `pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`
>
