### ISSUE TITLE
How to authenticate, if password has special character '&'?

### ISSUE THREAD

**Issue by venraju** [vgrem/Office365-REST-Python-Client#258]
Getting below error while authentication, my password has special character '&'. How it can be fixed?

Error:
An error occurred while retrieving token from XML response: AADSTS90023: Invalid STS request

**Comment by venraju** [comment]
It got fixed by below code
password = password.replace("&","&amp;")

**Comment by gcaringal** [comment]
@venraju's method has a typo. I believe it's supposed to be written as follows:
`password = password.replace("&", "&amp;")`

For reference, this is because there are certain characters that need to be escaped in XML. 

@vgrem Is this character-escape feature something that you think is important enough to implement? I'm new to open source contribution, but I'd like to make an attempt if you think it's useful.
