### ISSUE TITLE
How to filter items on a Sharepoint list that are in a list()

### ISSUE THREAD

**Issue by libora6** [vgrem/Office365-REST-Python-Client#279]
@vgrem just another small difficult that I found on my program here:

I want to filter only the items that are inside my list(), as the example below:
In this case I want to filter in the Sharepoint list all the data (select(*)) from the listname that have REQUEST_ID equal to those in the list ['e001292/201015141840', 'e001397/201015142045'].

`list_object = self.ctx.web.lists.get_by_title(listname)
items = list_object.get_items().select("*").filter("REQUEST_ID in ['e001292/201015141840', 'e001397/201015142045']")`

How do I do that? Was looking for some issues solved with that, but did not find anyone.

TKS

**Comment by vgrem** [comment]
Greetings,

the reason why the provided filter expressions fails is due to the fact  `IN` clause is _not_ supported in OData V3 which SharePoint API implements.

The way how IN operator could be constructed in OData V3 would be to replace it with multiple `OR` logical operator:  `<fieldname>  eq '<fieldvalue1>' or <fieldname>  eq '<fieldvalue2>'   ... <fieldname>  eq '<fieldvalueN>' `, for example

`items = list_object.get_items().select("*").filter("REQUEST_ID eq 'e001292/201015141840' or REQUEST_ID eq 'e001397/201015142045']")
`

Alternatively items could be retrieved via CAML query where `[IN` operator is supported](https://docs.microsoft.com/en-us/sharepoint/dev/schema/in-element-query), for example:

```

query_text = """
<Where>
        <In>
            <FieldRef Name="REQUEST_ID" />
            <Values>
                <Value Type="Text">e001292/201015141840</Value>
                <Value Type="Text">e001397/201015142045</Value>
            </Values>
        </In>
</Where>
"""
caml_query = CamlQuery.parse(query_text)
result = target_list.get_items(caml_query).execute_query() 

```
