### ISSUE TITLE
Content Type missing from files object

### ISSUE THREAD

**Issue by napsterstiffler** [vgrem/Office365-REST-Python-Client#355]
I have used the following code to get the file name and unique id for files on my sharepoint: 

```
files = ctx.web.lists.get_by_title(SP_DOC_LIBRARY).root_folder.files
ctx.load(files)
ctx.execute_query()

for file in files:
    print(file.properties['Name'], file.properties['UniqueId'])
```

However, I am not able to find content type in the properties. Is it expected here, or do i need to make a different call?

**Comment by vgrem** [comment]
Greetings!

This is expected since `ContentType` property [is not associated with `File `type](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542189(v=office.15)). Given the provided example  the content type of file could be retrieved like this (via [`ListItem.ContentType` property](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee538319(v=office.15))):


```
lib = ctx.web.lists.get_by_title("Documents")
files = lib.root_folder.files.expand(["listItemAllFields"]).get().execute_query()

for file in files:  # type: File
    print(f"{file.listItemAllFields.get_property('ContentTypeId')}")


```python 

lib = ctx.web.lists.get_by_title("Documents")
files = lib.root_folder.files.expand(["listItemAllFields"]).get().execute_query()

for file in files:  # type: File
    print(f"{file.listItemAllFields.get_property('ContentTypeId')}")
```
