### ISSUE TITLE
Office365 return None for properties after execute get_file_by_server_relative_url method

### ISSUE THREAD

**Issue by seniut** [vgrem/Office365-REST-Python-Client#370]
If I just open in browser:
`https://<base_url>/_api/web/GetFileByServerRelativeUrl('/sites/Data/Files/Wk12%20Hotel%20Report.xlsx')`

I got needed information like:
TimeCreated | "2021-06-23T11:11:55Z"
TimeLastModified | "2021-06-23T18:27:57Z"

![2021-06-25_17-51-22](https://user-images.githubusercontent.com/19908098/123443607-b9b47700-d5de-11eb-9bb8-5b00715cd99c.png)

But when I do it through python:
`result = get_conn().web.get_file_by_server_relative_url('/sites/Data/Files/Wk12 20Hotel 20Report.xlsx').execute_query()`
`get_conn()` - create connect to sharepoint

I get `None` for each properties:
![2021-06-25_18-01-53](https://user-images.githubusercontent.com/19908098/123447408-7b20bb80-d5e2-11eb-9fe4-ef2685f604ec.png) 
And if try to get last modified date of file:
 `result = get_conn().web.get_file_by_server_relative_url(file_url).time_last_modified().execute_query()`
Got error: `TypeError: 'NoneType' object is not callable`

**Comment by vgrem** [comment]
Hi,

the empty `properties` is expected here since `File` resource is not getting retrieved in the provided example:
 
`result = get_conn().web.get_file_by_server_relative_url('/sites/Data/Files/Wk12 20Hotel 20Report.xlsx').execute_query()`


Along with `web.get_file_by_server_relative_url(file_url)` method  `get` method needs to be explicitly invoked  (to construct a retrieve a get query) to retrieve a file metadata, like this:

`file = ctx.web.get_file_by_server_relative_url(file_url).get().execute_query()`

The reasoning here,  other than `get` it could another operations (`delete` for instance). By specifying it, allows to _avoid_ any ambiguity in terms of operation that needs to be performed against addressed resource

  
thank you for the provided details,
Vadim

**Comment by seniut** [comment]
@vgrem Thank you a lot!!! I got at. It is my mistake 
Now It works perfect.
Very appreciate your fast feedback and your spend time. Many thanks
