### ISSUE TITLE
 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by bharatsangale1** [vgrem/Office365-REST-Python-Client#372]
Getting Below error while connecting to SharePoint online.

**Exception:**
 File "C:\Users\sangbha\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

**Code**
ctx = ClientContext(site_url).with_user_credentials("USER@COMPANY_NAME.com", "PASSWORD")
    web = ctx.web.get().execute_query()
    print(web.url)

Please let me know if I am missing anything.

**Comment by mayankbakhru** [comment]
@vgrem 
I am getting same error while trying to upload the file. this is because MS has stopped supporting lower TLS protocols.
I am able to successfully connect to sharepoint using request.verify=False but when I execute 'ctx.execute_query()' for uploading the file I get [SSL: CERTIFICATE_VERIFY_FAILED]
Can you help?
===============My Code==================
site_url = "https://{tenant}.sharepoint.com/"
ctx = ClientContext(site_url).with_credentials(UserCredential('USERNAME', 'PWD'))

request = RequestOptions("{0}/_api/web/".format(site_url))
request.verify = False
response = ctx.execute_request_direct(request)
json = json.loads(response.content)
web_title = json['d']['Title']
print("Web title: {0}".format(web_title))

folder_url_shrpt = '[addition to URL]'

def upload_file(ctx,fileName,folder_url_shrpt):
    path = "c:/temp/autorefresh/"+fileName
    with open(path, 'rb') as content_file:
        file_content = content_file.read()

    target_folder = ctx.web.get_folder_by_server_relative_url(folder_url_shrpt)
    name = os.path.basename(path)
    target_file = target_folder.upload_file(name, file_content)
    ctx.execute_query()
    print("File has been uploaded to url: {0}".format(target_file.serverRelativeUrl))

upload_file(ctx, "<filename>",folder_url_shrpt)

**Comment by mayankbakhru** [comment]
I was able to get past the SSL error by disabling SSL.
Code is taken from this repo.
def disable_ssl(request):
    request.verify = False  # Disable certification verification
Before executing execute_query() you can call the disable function defined above. 
    ctx.pending_request().beforeExecute += disable_ssl
    ctx.execute_query()

Note - you'll get some warnings about not using secure protocol
