### ISSUE TITLE
How to access permissions on ListItem

### ISSUE THREAD

**Issue by RobinVds** [vgrem/Office365-REST-Python-Client#440]
Is there a way to access permissions on ListItem level? 
I'm trying this but it seems not to be working:

`        for item in items:
            item: ListItem = item
            ra_collection = item.role_assignments
            for ra in ra_collection:
                ra: RoleAssignment
`

If this is not possible, what would be the easiest way to get the permissions of a user on a specific file? I'm trying to mirror file permissions in my app.

**Comment by vgrem** [comment]
Greetings,

since `ListItem.RoleAssignments` is a navigation property, it needs to be retrieved _explicitly_ via `$expand` query option, like this: 

```python
file = ctx.web.get_file_by_server_relative_url(file_url)
file_item = file.listItemAllFields.expand(["roleAssignments"]).get().execute_query()  # type: ListItem
```


To  get the effective permissions on the list item that are assigned to the current user, use [`ListItem.EffectiveBasePermissions` property](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542699(v=office.15)):


```python
file = ctx.web.get_file_by_server_relative_url(file_url)
file_item = file.listItemAllFields.select(["EffectiveBasePermissions"]).get().execute_query()  # type: ListItem
pprint(file_item.effective_base_permissions.permission_levels)
```
