### ISSUE TITLE
Can I safely construct a user's login name?

### ISSUE THREAD

**Issue by RobinVds** [vgrem/Office365-REST-Python-Client#446]
I'm trying to check the permissions of a user. If I'm correct, I need to use a relative site_url to retrieve a user to be able to check if he has permissions. It could be that a user has permissions on an object but is not yet a member of a specific site. That's why I'm now trying to do something like this:

```
    def _check_if_user_has_permission(self, relative_file_url: str, user_email: str):        
        sharepoint_site_ctx = self.sharepoint_connection.get_ctx()
        result = sharepoint_site_ctx.web.get_file_by_server_relative_path(
            relative_file_url
        ).listItemAllFields.get_user_effective_permissions(
            "i:0#.f|membership|"+user_email
        ).execute_query()

        return result.value.has(PermissionKind.OpenItems)
```

Is this safe to construct the user's login name in this way? Or is there a way how I can get the user's login name independent of the site url?

**Comment by vgrem** [comment]
Greetings,

for the most cases that would work as expected but i would rather avoid it construct that way. Identity claim format might differ, e.g. depending on provider type (refer [this article](https://social.technet.microsoft.com/wiki/contents/articles/13921.sharepoint-20102013-claims-encoding.aspx) for a more details)

Consider to pass `User.LoginName` property into `SecureObject.get_user_effective_permissions` instead.  `User.LoginName` could be determined via `UserCollection.site_users.get_by_email` method, for example: 

```python 
user = client.web.site_users.get_by_email(user_email).get().execute_query()
result = file.listItemAllFields.get_user_effective_permissions(user.login_name).execute_query()
```

or via more _shorter_ version (since `UserCollection.get_user_effective_permissions` method also accepts `User` type):

```
user = client.web.site_users.get_by_email(user_email)
result = target_file.listItemAllFields.get_user_effective_permissions(user).execute_query()
```
