### ISSUE TITLE
# in file name creates invalid URL

### ISSUE THREAD

**Issue by RobinVds** [vgrem/Office365-REST-Python-Client#464]
When I try to download a file with a title like: `A random title # some text` I get the following error:
`Microsoft.SharePoint.SPException', 'The file /sites/randomSite/A random title  does not exist.`

It seems that the part starting from the `#` is removed.

**Comment by vgrem** [comment]
Greetings,

> It seems that the part starting from the # is removed.

indeed it is. And this is something related with SharePoint API implementation itself. The root cause why special symbols (namely` #)` is summarized in [Supporting `% `and` #` in files and folders with the ResourcePath API](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api):

> Support for % and # in files and folders is being deployed within SharePoint Online. Unfortunately, due to existing API structures and calling patterns, working with these file names can sometimes become ambiguous.


**Resolution**
When addressing files, _prefer_ `Web.get_file_by_server_relative_path(path) `over `Web.get_file_by_server_relative_url(url)` method, same goes to another resources (e.g. Folders).

Similar thread: How to access remote files on the server with special characters in their names? #316
