### ISSUE TITLE
is any different for the 2 methods to get the SharePoint items?

### ISSUE THREAD

**Issue by braveru** [vgrem/Office365-REST-Python-Client#551]
Hi , @vgrem 

is any different for below 2 methods to get the SharePoint items?
as I use both in same script , they all can get the items completely .
my list items count may over ten thousand , but now just 2000+ items , so I need to know there different , 

thank you so much .

```
items = target_list.items.paged(50).get().execute_query()
items = target_list.items.top(1000000).get().execute_query()  
```
by the way , I use your sample code as below , always report error : **paged() got an unexpected keyword argument 'page_loaded'**
```
items = target_list.items.paged(50, page_loaded=print_progress).get().execute_query()
```

**Comment by vgrem** [comment]
Greetings @braveru,

The error most likely occurs since `paged` method signature has changed (the changes are expected to be included in the next `2.4.0` version although the changes already has been reflected in `examples` section), sorry for the inconvenience. 


The rationale behind `paged` method  is the support for the _pagination for large result sets_ (and apparently to mitigate  the risk of being throttled by API), lets compare the two: 

- `items = target_list.items.top(<N>).get().execute_query() `   

- `items = target_list.items.paged(<N>).get().execute_query()`  

The first example is behaving as expected, namely only the first `N` items gets retrieved from the server,  while in the second one: 

- first N items gets retrieved on the first request  
- next items gets retrieved on subsequent requests to retrieve the remaining items (lazy evaluation)
 
```python  
paged_items = target_list.items.paged(50, page_loaded=print_progress).get().execute_query() # retrieve 50 items from first page  
for index, item in paged_items:     
    print("{0}".format(item.id))
```





And finally there is a `get_all` method which is intended for retrieving all the items:  items = target_list.items.get_all().execute_query()

**Comment by braveru** [comment]
thank you [vgrem](https://github.com/vgrem) , I got the answer .

**Comment by tm-kobe-deluna** [comment]
@vgrem I have the following code:

```
target_folder_url = "Documents"

large_list = ctx.web.get_folder_by_server_relative_path(target_folder_url)

paged_items = (
    large_list.files.paged(50, page_loaded=print_progress).get().execute_query()
)  # retrieve 50 items from first page
for index, item in enumerate(paged_items):
    print("{0}".format(item.name))
```

I was able to get the first 50 items in the first page but how can I retrieve the next items?
