### ISSUE TITLE
Enumerate all files from a specific folder

### ISSUE THREAD

**Issue by timepasser69** [vgrem/Office365-REST-Python-Client#586]
How to enumerate all the files from specific folder? This folder can have subfolders. In the guide, it shows the enumeration from the root only.

**Comment by florinmihut-intel** [comment]
You could try this (have a look at the examples: [list_files.py](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/list_files.py))

If you just want the files from a specific folder, do this (let's assume that your Shared Documents has a folder called Manufacturing you might want to list):
folder = self.ctx.web.get_folder_by_server_relative_path("Shared Documents/Manufacturing")
files = folder.get_files(True).execute_query() # True if you want to recurse in the subfolders, False otherwise
[f.properties['ServerRelativeUrl'] for f in files]

So get_folder_by_server_relative_path is accepting any server relative path not just the "Shared Documents" as given in the example. Just play around and see what you get.

**Comment by timepasser69** [comment]
I get this error:

AttributeError                            Traceback (most recent call last)
Input In [9], in <cell line: 2>()
      1 folder = ctx.web.get_folder_by_server_relative_path("Shared Documents/output")
----> 2 files = folder.get_files(True).execute_query()

AttributeError: 'Folder' object has no attribute 'get_files'

**Comment by Hmr-ramzi** [comment]
@timepasser69 on my side it works fine. Looks like you have another issue can you please share the whole code snippet?

**Comment by timepasser69** [comment]
> @timepasser69 on my side it works fine. Looks like you have another issue can you please share the whole code snippet?

here is my code:

`def enum_folder(parent_folder, fn):
    """
    :type parent_folder: Folder
    :type fn: (File)-> None
    """
    parent_folder.expand(["Files", "Folders"]).get().execute_query()
    for file in parent_folder.files:  # type: File
        fn(file)
    for folder in parent_folder.folders:  # type: Folder
        enum_folder(folder, fn)


def print_file(f):
    """
    :type f: File
    """
    print(f.properties['ServerRelativeUrl'])


target_folder_url = "Shared Documents/output"
root_folder = ctx.web.get_folder_by_server_relative_path(target_folder_url)
#enum_folder(root_folder, print_file)

files = root_folder.get_files(True).execute_query()
[print_file(f) for f in files]`

**Comment by Hmr-ramzi** [comment]
I would suggest trying to get a file instead of a folder first. Just make sure you have the right credentials for the context and make sure you can download maybe one file. The code should work fine if you pass the right credentials and give the right "Relative" path

**Comment by rchua-at-synagie** [comment]
The example script downright just doesn't work for me. Tested on version 2.3.11 and 2.3.15

I am getting 
AttributeError: 'Folder' object has no attribute 'get_files'

**Comment by vgrem** [comment]
Hi there,

in [`2.5.1` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.1)  was introduced `Folder.get_files(recursive)` method 

> where 
>    `recursive` flag determines whether to enumerate folders recursively


which allows to enumerate files within a folder. Here is an example on how to retrieve all the files from a folder including sub folders:


```python
ctx = ClientContext(test_team_site_url).with_credentials(user_credentials)
target_folder_url = "Shared Documents/Archive"
root_folder = ctx.web.get_folder_by_server_relative_path(target_folder_url)
files = root_folder.get_files(True).execute_query()
```
