### ISSUE TITLE
Question: How to extract file creator name instead principle.user.User object for file in the sharepoint folder using  file.modified_by  function

### ISSUE THREAD

**Issue by samrackson** [vgrem/Office365-REST-Python-Client#587]
Hi, 

Currently I am trying to fetch SharePoint file properties information with author name/modified user name. 

I tried extracting the file properties from the SharePoint by using "file.modified_by" function. Whereas, it prints out principal.user.User object instead of profilename/username.

sample output info extracted for file.modified_by:
'modified_by': <office365.sharepoint.principal.user.User object at <>>

Could you please advice, how can we extract the author profile_name from the object ?

Kindly share sample python code snippet if there is any. 
 
Thanks!

**Comment by vgrem** [comment]
Greetings,

since `ModifiedBy` is a projected field from `User Information List` list, `$expand` query option could be utilized which  allows to return `ModifiedBy` _projected_ property along with another properties: 


```python
file = ctx.web.get_file_by_server_relative_url(file_url).expand(["ModifiedBy"]).get().execute_query()
print("File modified by: {0}".format(file.modified_by.properties.get('UserPrincipalName')))
```


### References 

[Use OData query operations in SharePoint REST requests](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
