### ISSUE TITLE
No module named 'office365.sharepoint.files.file_system_object_type'

### ISSUE THREAD

**Issue by sant3e** [vgrem/Office365-REST-Python-Client#603]
I wanted to use this package. At first all: from ... import were failing. 
I googled and found that if i install also office365, might work .. didn't... googled some more, found that i need to install both office365 and Office365-REST-Python-Client under the Scripts folder... did so ... now, all but one import still fails (the sharepoint.fiels)
Googled some more found a suggestion to go with a specific version (2.3.11) .. still no go. 
Tried last version (2.3.17).. still no go ... I am all out of ideas

I get these 2 errors:
```
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```
For this urllib3 -chardet missmatch I also tried alot of combos for both (downgrading and upgrading them all, including requests ... i just don't seem to hit the proper one.
```
Traceback (most recent call last):
  File "c:\xxx\REPO Projects\SFS2DB\sp_app_download_all.py", line 9, in <module>
    from office365.sharepoint.files.file_system_object_type import FileSystemObjectType    
ModuleNotFoundError: No module named 'office365.sharepoint.files.file_system_object_type
```

**Comment by vgrem** [comment]
Hi,

it appears the provided error occurs since a different _`requests` module installed by the OS and the python dependencies for your local installation_, refer [this thread](https://stackoverflow.com/questions/50202238/python-pip-requestsdependencywarning-urllib3-1-9-1-or-chardet-2-3-0-doe) for a more details on how to  resolve it.


Alternately, consider to create an isolated environment, for instance via `venv` to avoid upgrading the packages installed globally:

- create a virtual environment: `python -m venv .env`
- activate a virtual environment `source env/bin/activate`
- and finally install a package: `pip install Office365-REST-Python-Client`


**Minimal example**

```python
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.client_credential import ClientCredential
site_url  = "https://{your-tenant-prefix}.sharepoint.com"
client_credentials = ClientCredential('---client_id--','--client_secret--')


ctx = ClientContext(site_url).with_credentials(client_credentials)
target_web = ctx.web.get().execute_query()
print(target_web.url)

```

**References**

[Installing packages using pip and virtual environments ](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/)
