### ISSUE TITLE
Storage Size & Metrics

### ISSUE THREAD

**Issue by matteoaurelio** [vgrem/Office365-REST-Python-Client#621]
I am trying to access the storage metrics from folders
``
folders = root_folder.folders
ctx.load(folders)
ctx.execute_query()

for folder in folders:
    #print(dir(folder.storage_metrics.properties))
    print(folder.storage_metrics.properties.keys())

``

But all the storage metrics are None and all the dictionary is empty as well.

How can I access the storage metrics report from folders ?

Thank you,
Matteo

**Comment by vgrem** [comment]
Greetings,

this is the expected behavior since [`Folder.StorageMetrics`](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/a9e296ef-3065-418b-82c0-0ddbac395f3f) is a [navigation property](https://learn.microsoft.com/en-us/odata/webapi/complextypewithnavigationproperty) it needs ti be requested _explicitly_, for example:


```pythpn
folders = lib.root_folder.folders
ctx.load(folders, ["StorageMetrics"])
ctx.execute_query()
```


or via nested syntax:

```python
folders = lib.root_folder.folders.get().expand(["StorageMetrics"]).execute_query()

for folder in folders:  # type: Folder
    print(folder.storage_metrics.properties)
```
