### ISSUE TITLE
Enumerate all sites that the current user account has access to

### ISSUE THREAD

**Issue by tigre-bleu** [vgrem/Office365-REST-Python-Client#640]
I try to create a script that will list all sites the current user can access. 

I see a function to get a list of all sites using admin privileges, but I need to use the low priv credentials of the user himself.

Is there a way to do that?

Thanks

**Comment by vgrem** [comment]
Greetings, 

the following options could be considered:


### Approach 1: via Search based API

Only the sites that the current user account has access to are getting returned since search API performs security trimming of search results that are based on the identity of the user submitting the query. 

```python
ctx = ClientContext(site_url).with_credentials(user_credentials)
result = ctx.search.query("contentclass:STS_Site").execute_query()
results = result.value.PrimaryQueryResult.RelevantResults
for row in results.Table.Rows:
    print(row.Cells["Path"])  # prints site url

```

### Approach 2: query based


I would suggest to prefer approach 1 over this one since:

- it requires a privileged access to Tenant API 
- performance suffers since the the filtering (whether the user has access to) is applied on the client side  


```python
admin_client = ClientContext(admin_site_url).with_credentials(admin_credentials)
tenant = Tenant(admin_client)
result = tenant.get_site_properties_from_sharepoint_by_filters("").execute_query()

def try_get_user_permissions(site_url, user_name):
    ctx = ClientContext(site_url).with_credentials(admin_credentials)
    try:
        perms_result = ctx.web.get_user_effective_permissions(user_name).execute_query()
        #todo: determine user permissions from result
        return True
    except ClientRequestException as e:
        if e.response.status_code == 404:
            return False
        else:
            raise ValueError(e.response.text)


for siteProps in result:  # type: SiteProperties
    print("Current site url: {0}".format(siteProps.url))
    if try_get_user_permissions(siteProps.url, test_user_principal_name) is True:
        print("Site url {0} {1} user has access to".format(siteProps.url, test_user_principal_name))

```
