### ISSUE TITLE
No "Create folder" only "Ensure folder path"

### ISSUE THREAD

**Issue by lokefar** [vgrem/Office365-REST-Python-Client#695]
I'm looking into creating folders, and as fare as I can see in the documentation the only way to create a folder is to use 
`target_folder = ctx.web.ensure_folder_path(target_folder_url).execute_query()` as in the example: [Created nested Folder](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/folders/create_nested_folders.py)

However in my use-cases this trickers and returns an "Not authenticated" error eventhough the folder is still created within the Sharepoint folder.

Two questions:
1) Are there another, better way to create folders?
2) Any recommendations where to dig deeper into this is very much appreciated

Thank you!

**Comment by vgrem** [comment]
Greetings,

the _common_ way to create a new folder would be to utilize  `FolderCollection.add(name)` or `FolderCollection.add_using_path(name, overwrite)` methods which:

> Adds the folder that is located under a current folder. The official documentation could be found [here](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee541867(v=office.15))

Example: creates a  folder in Documents library 

```python
folder_name = "Reports"  
folder = ctx.web.default_document_library().root_folder.folders.add_using_path(folder_name, overwrite=True).execute_query()

```

`Web.ensure_folder_path(path)` is more _advanced_ option, since `path` could point to `web-relative path` and folder gets created if it do not exist
