### ISSUE TITLE
View all files in my Document Library

### ISSUE THREAD

**Issue by judeabii** [vgrem/Office365-REST-Python-Client#715]
I did use the code (traverse.py) but my document library size is above 5000. How can I implement ListItemCollection in Python, presumably with a caml query?

**Comment by vgrem** [comment]
The library suppports working with large lists & libraries, in case of `traverse.py` example `get_all()` method could be used instead of `get()` to retrive all the items, for example:

`items = doc_lib.items.select(["FileSystemObjectType"]).expand(["File", "Folder"]).get_all().execute_query()  `


For a more details, refer:

- [Retrieving all items in a collection](https://github.com/vgrem/Office365-REST-Python-Client/wiki/Handling-Large-Lists) wiki
- [`read_large.py` example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/lists/read_large.py) which demonstrates how to read large lists

**Comment by Kugeleis** [comment]
Even if I run
```
from office365.sharepoint.files.system_object_type import FileSystemObjectType
from office365.sharepoint.listitems.listitem import ListItem

expander = ["File", "Folder"]
page_size = 50000

doc_lib = ctx.web.default_document_library()
items = (
    doc_lib.items.select(["FileSystemObjectType"])
    .expand(expander)
    .get_all(page_size)
    .execute_query()
)
for idx, item in enumerate(items):  # type: int, ListItem
    if item.file_system_object_type == FileSystemObjectType.Folder:
        print(
            "({0} of {1})  Folder: {2}".format(
                idx, len(items), item.folder.serverRelativeUrl
            )
        )
    else:
        print(
            "({0} of {1}) File: {2}".format(
                idx, len(items), item.file.serverRelativeUrl
            )
        )
```
regardless of page_size I only get the first n items. I have ~300 files in <10 folders and need to list them all. How to do this?
