### ISSUE TITLE
Need some guidance to optimize the performance of List Items Deletion

### ISSUE THREAD

**Issue by nkgxgongxi** [vgrem/Office365-REST-Python-Client#725]
Hi there, 

Sorry if I used issue creation in a wrong way. I am a newbie with github and still learning others how to interact with community more professionally. 

Firstly would like to say huge thank you for this Python Library to interact with MS products. It helps a lot for our team's automation. 
One issue we are facing is the relatively low performance deleting/inserting items from/into a Sharepoint List. We have some lists with several tens of thousands of records to support some PowerApp tools, and the ask is to have the backend data refreshed in automated fashion. I have created some scripts leveraging your library to handle the requirement, but it took about 90 seconds to delete every 1000 records so the whole script will take about one hour to complete one round of data refresh. 

I have tried searching examples from your codebase but didn't find specific places about how I can tune the performance. So far what I have tried is to execute in batch and process every 1000 records. In addition, when I tried to insert the records I also have to put some sleep time between each batch upload to avoid triggering maximal retries within too short periods. 

Any thoughts or guidance on how I can make things more smooth? I will sincerely appreciate your help!
Regards

**Comment by vgrem** [comment]
Greetings!

One aprorach to consider is to utilize `ClientContext.execute_batch()` method instead of `ClientContext.execute_query()`  which in a nutshell allows to combine many operations into a single request and submit to the server. 

The following example demonstrates how to delete multiple list items via batch request:

```
for item in items:  # type: ListItem
    item.delete_object()
ctx.execute_batch()

```

Example: [`delete_batch.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/listitems/delete_batch.py)
