### ISSUE TITLE
resource_path is not a str? or is a str type? 

### ISSUE THREAD

**Issue by netist123** [vgrem/Office365-REST-Python-Client#74]
I'm trying to get the view list of views by using the example, but always met such issue. 
could you help? 

========== code
url="https://xxx.sharepoint.com/sites/xxxx"
ctx_auth = AuthenticationContext(url)
if ctx_auth.acquire_token_for_user(username, password):
  
  ctx = ClientContext(url, ctx_auth)
  
   web = ctx.web
  #print("web resource_path{}".format(web.resource_path))
  
  ctx.load(web)
  ctx.execute_query()
  print ("Web title: {0}".format(web.properties['Title']))

  
  issue here when calling -> print_list_views(ctx)

======================

File "C:\python36\lib\site-packages\office365\sharepoint\view_collection.py", line 10, in get_by_title
    resourcePath = self.resource_path + "/getbytitle('{0}')".format(view_title)
TypeError: unsupported operand type(s) for +: 'ResourcePathEntry' and 'str'

**Comment by vgrem** [comment]
Greetings,

since this error has been resolved already in a later releases, propose to close it.

At the moment library supports CRUD operations against [`View` resource](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn531433(v=office.15)?redirectedfrom=MSDN#view-resource)


### Examples

Let's assume `Tasks` list instance exist in a site 

```
client = ClientContext("https://contoso.sharepoint.com/", ctxAuth)
target_list = client.web.lists.get_by_title("Tasks")
```

then the following examples demonstrate how to perform CRUD operations with Views:

**Create a view** 

```
view_properties = ViewCreationInformation()
view_properties.Title = "My Tasks"
view_properties.PersonalView = True
view_properties.Query = "<Where><Eq><FieldRef ID='Assigned To' /><Value " \
                                "Type='Integer'><UserID/></Value></Eq></Where> "

view_to_create = target_list.views.add(view_properties)
client.execute_query()
```


**Read a view**

Get a specific view by title:

```
view_to_read = target_list.views.get_by_title("My Tasks")
client.load(view_to_read)
client.execute_query()
```


**Update a view**

Update `Title `property

```
view_to_update = target_list.views.get_by_title("My Tasks")
view_to_update.set_property('Title', "My Tasks for 2020")
view_to_update.update()
client.execute_query()
```

**Delete a view** 

```
view_to_delete = target_list.views.get_by_title("My Tasks")
view_to_delete.delete_object()
client.execute_query()
```

**Comment by netist123** [comment]
great. thanks！
