### ISSUE TITLE
Unable to run example web_read_direct.py

### ISSUE THREAD

**Issue by codyrhowe** [vgrem/Office365-REST-Python-Client#81]
When attempting to run the example web_read_direct.py the following error is thrown:

Traceback (most recent call last):
  File "web_read_direct.py", line 19, in <module>
    data = ctx.execute_request_direct(options)
AttributeError: 'ClientContext' object has no attribute 'execute_request_direct'

I checked the client_context.py file and in fact there is no execute_request_direct, so I looked at client_request.py and there is a def for execute_request_direct, so I updated the code to use ClientRequest, but still get the following error.

Traceback (most recent call last):
  File "web_read_direct.py", line 19, in <module>
    data = request.execute_request_direct(options)
AttributeError: 'ClientRequest' object has no attribute 'execute_request_direct'

What am I doing wrong?

**Comment by vgrem** [comment]
Hello,

it seems you are utilizing the  library version v2.0.0, which  is available in python package index, right? If so, `ClientRuntimeContext.execute_query_direct` could to be utilized instead of `ClientRuntimeContext.execute_request_direct` but i would suggest a different solution.

 
The point is, version `v2.0.0` which is referenced in pip a bit outdated at the moment. It has already [been reported](https://github.com/vgrem/Office365-REST-Python-Client/issues/75) . But you could consider to  install the **latest** version (`2.1.1`) from GitHub instead, like this:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

Please refer [this answer](https://stackoverflow.com/a/50429966/1375553) for a more details.
 
Vadim

**Comment by codyrhowe** [comment]
Hi Vadim,

I updated per your instructions and this is working now. Thanks so much for the quick response.

Regards,
Cody
